<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container7iwXWo4\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container7iwXWo4/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container7iwXWo4.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container7iwXWo4\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container7iwXWo4\App_KernelDevDebugContainer([
    'container.build_hash' => '7iwXWo4',
    'container.build_id' => 'd0b94888',
    'container.build_time' => 1696769432,
], __DIR__.\DIRECTORY_SEPARATOR.'Container7iwXWo4');
